version: '3.9'

services:

  nginx:
    image: nginx:latest
    depends_on:
      - wp
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx 
    ports:
      - "80:80"

  wp:
    image: wordpress #:6.1.1 # https://hub.docker.com/_/wordpress/
    container_name: "${APP_NAME}_wordpress"
    ports:
      - ${WP_PORT}:80 # change ip if required
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html/subfolder # Full wordpress project
      - /Users/yiannistaos/Projects/extensions-without-generator/wp-login-as-user/src/login-as-user/:/var/www/html/subfolder/wp-content/plugins/login-as-user # Plugin development
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
      WORDPRESS_TABLE_PREFIX: "${WP_TABLE_PREFIX}_"
    depends_on:
      - db
    links:
      - db

  pma:
    image: arm64v8/phpmyadmin
    container_name: "${APP_NAME}_phpmyadmin"
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      UPLOAD_LIMIT: 50M
    ports:
      - ${PHPMYADMIN_PORT}:80
    links:
      - db:db

  db:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    container_name: "${APP_NAME}_database"
    ports:
      - ${DB_PORT}:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

